---
version: '3'

volumes:
  k3s-server: {}

networks:
  outer: ~
  inner:
    internal: true

services:
  # Inner networks cannot have any port forwarded directly.
  # Service forwarding TCP traffic received on port 6443
  # to the server on port 6443.
  kubegateway:
    image: alpine:3.10.0
    ports:
      - 6443:6443
    command:
      - "nc"
      - "-lk"
      - "-p"
      - "6443"
      - "-e"
      - "/usr/bin/nc"
      - "server"
      - "6443"
    networks:
      - outer
      - inner

  squid:
    image: sameersbn/squid:3.5.27-1
    networks:
      - outer
      - inner

  server:
    image: rancher/k3s:v0.6.1
    command: server --disable-agent -no-deploy traefik
    environment:
      - K3S_CLUSTER_SECRET=somethingtotallyrandom
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      # This is just so that we get the kubeconfig file out
      - ./output:/output
    ports:
      - 6443:6443
    networks:
      - inner

  node:
    image: rancher/k3s:v0.6.1
    tmpfs:
      - /run
      - /var/run
    privileged: true
    depends_on:
      - server
    environment:
      - K3S_URL=https://server:6443
      - K3S_CLUSTER_SECRET=somethingtotallyrandom
    volumes:
      - ./images:/var/lib/rancher/k3s/agent/images
    networks:
      - inner
